<?php

namespace portalium\workspace\components;

use portalium\base\Event;
use portalium\site\models\Setting;
use portalium\workspace\models\WorkspaceUser;
use portalium\workspace\Module;
use Yii;
use yii\base\BaseObject;

class TriggerActions extends BaseObject
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    /* 
        public function onUserDeleteBefore($event)
        {
            ['id' => $id_user, 'default_user' => $defaultUser, 'action' => $action] = $event->payload;
            if ($action == 'delete') {
                $workspaces = Workspace::find()->where(['id_user' => $id_user])->all();
                foreach ($workspaces as $workspace) {
                    $workspace->delete();
                }
                

            }elseif($action == 'transfer'){
                if ($defaultUser) {
                    $workspaces = Workspace::find()->where(['id_user' => $id_user])->all();
                    foreach ($workspaces as $workspace) {
                        $workspace->id_user = $defaultUser;
                        $workspace->save();
                    }
                }
            }
        }
     */

    public function onRoleDeleteBefore($event)
    {
        ['item' => $item] = $event->payload;

        $this->deleteWorkspaceUserRoles($item->name);
    }

    private function deleteWorkspaceUserRoles($roleName)
    {
        $workspaceUserRoles = WorkspaceUser::find()->where(['role' => $roleName])->all();

        foreach ($workspaceUserRoles as $workspaceUserRole) {
            $workspaceUserRole->delete();
        }
    }

    public function onRoleUpdateBefore($event)
    {
        ['item' => $item, 'oldItem' => $oldItem] = $event->payload;


        $this->updateWorkspaceUserRoles($item->name, $oldItem->name);
    }

    private function updateWorkspaceUserRoles($roleName, $oldRoleName)
    {
        $workspaceUserRoles = WorkspaceUser::find()->where(['role' => $oldRoleName])->all();

        foreach ($workspaceUserRoles as $workspaceUserRole) {
            $workspaceUserRole->role = $roleName;
            $workspaceUserRole->save();
        }
    }

    public function onSettingUpdateAfter($event)
    {
        ['data' => $data, 'changedAttributes' => $changedAttributes] = $event->payload;
        
        if($data['name'] == 'workspace::available_roles'){
            $oldRoles = [];
            if(isset($changedAttributes['value'])){
                foreach (json_decode($changedAttributes['value']) as $module => $roles) {
                    foreach ($roles as $role) {
                        $oldRoles[] = [
                            'module' => $module,
                            'role' => $role
                        ];
                    }
                }
            }
            $newRoles = [];
            if(isset($data['value'])){
                foreach (json_decode($data['value']) as $module => $roles) {
                    foreach ($roles as $role) {
                        $newRoles[] = [
                            'module' => $module,
                            'role' => $role
                        ];
                    }
                }
            }


            $deletedRoles = [];
            foreach ($oldRoles as $oldRole) {
                if(!in_array($oldRole, $newRoles)){
                    $deletedRoles[] = $oldRole;
                }
            }
            if($deletedRoles){
                foreach ($deletedRoles as $deletedRole) {
                    $checkRolesWorkspaceUser = WorkspaceUser::find()->where(['role' => $deletedRole['role'], 'id_module' => $deletedRole['module']])->one();
                    if($checkRolesWorkspaceUser){
                        $settingModel = Setting::findOne(['name' => 'workspace::available_roles']);
                        $settingModel->value = $changedAttributes['value'];
                        $settingModel->save();
                        Yii::$app->session->addFlash('error', Yii::t('workspace', 'You can not delete this role because it is used in workspace.'));
                        break;
                    }
                }
            }else{
                $deletedRoles = [];
            }
            
            Event::trigger(Yii::$app->getModules(), Module::EVENT_ROLE_UPDATE_AFTER, new Event(['payload' => [
                'deletedRoles' => $deletedRoles
            ]]));
        }
    }
}