<?php

namespace portalium\workspace\components;

use portalium\workspace\models\WorkspaceUser;
use Yii;
use yii\base\BaseObject;

class TriggerActions extends BaseObject
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    /* 
        public function onUserDeleteBefore($event)
        {
            ['id' => $id_user, 'default_user' => $defaultUser, 'action' => $action] = $event->payload;
            if ($action == 'delete') {
                $workspaces = Workspace::find()->where(['id_user' => $id_user])->all();
                foreach ($workspaces as $workspace) {
                    $workspace->delete();
                }
                

            }elseif($action == 'transfer'){
                if ($defaultUser) {
                    $workspaces = Workspace::find()->where(['id_user' => $id_user])->all();
                    foreach ($workspaces as $workspace) {
                        $workspace->id_user = $defaultUser;
                        $workspace->save();
                    }
                }
            }
        }
     */

    public function onRoleDeleteBefore($event)
    {
        ['item' => $item] = $event->payload;
        Yii::warning($item->name);
        $this->deleteWorkspaceUserRoles($item->name);
    }

    private function deleteWorkspaceUserRoles($roleName)
    {
        $workspaceUserRoles = WorkspaceUser::find()->where(['role' => $roleName])->all();

        foreach ($workspaceUserRoles as $workspaceUserRole) {
            $workspaceUserRole->delete();
        }
    }

    public function onRoleUpdateBefore($event)
    {
        ['item' => $item, 'oldItem' => $oldItem] = $event->payload;
        Yii::warning($item->name);
        Yii::warning($oldItem->name);
        $this->updateWorkspaceUserRoles($item->name, $oldItem->name);
    }

    private function updateWorkspaceUserRoles($roleName, $oldRoleName)
    {
        $workspaceUserRoles = WorkspaceUser::find()->where(['role' => $oldRoleName])->all();

        foreach ($workspaceUserRoles as $workspaceUserRole) {
            $workspaceUserRole->role = $roleName;
            $workspaceUserRole->save();
        }
    }
}